service: currency-exchange-notifier

package:
  individually: true

custom:
  ${file(config/custom.yml)}

plugins:
  - serverless-pseudo-parameters
  - serverless-webpack
  - serverless-offline
  
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: ${opt:stage, 'sandbox'}
  iamRoleStatements:
    ${file(config/role-statements/common.yml)}
  lambdaHashingVersion: '20201221'


functions:
  - ${file(config/functions/notify-by-mail.yml)}

resources:
  - ${file(config/resources/api-gateway.yml)}
